DROP TABLE IF EXISTS `USERS`;
CREATE TABLE `USERS` (
    `USER_ID`    BIGINT       NOT NULL AUTO_INCREMENT COMMENT '사용자 ID',
    `USER_NAME`  VARCHAR(64)  NOT NULL COMMENT '사용자 이름',
    `CREATED_AT` DATETIME     NOT NULL COMMENT '생성일시',
    `UPDATED_AT` DATETIME     NOT NULL COMMENT '수정일시',
    PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT = '사용자';

DROP TABLE IF EXISTS `PRODUCTS`;
CREATE TABLE `PRODUCTS` (
    `PRODUCT_ID`     BIGINT       NOT NULL AUTO_INCREMENT COMMENT '상품 ID',
    `PRODUCT_NAME`   VARCHAR(100) NOT NULL COMMENT '상품 이름',
    `PRODUCT_STATUS` VARCHAR(64)  NOT NULL COMMENT '상품 상태',
    `CREATED_AT`     DATETIME     NOT NULL COMMENT '생성일시',
    `UPDATED_AT`     DATETIME     NOT NULL COMMENT '수정일시',
    PRIMARY KEY (`PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT = '상품';

DROP TABLE IF EXISTS `EVENTS`;
CREATE TABLE `EVENTS` (
    `EVENT_ID`           BIGINT       NOT NULL AUTO_INCREMENT COMMENT '이벤트 ID',
    `EVENT_NAME`         VARCHAR(100) NOT NULL COMMENT '이벤트 이름',
    `EVENT_TYPE`         VARCHAR(64)  NOT NULL COMMENT '이벤트 유형',
    `START_DT`           DATETIME     NOT NULL COMMENT '이벤트 시작일시',
    `END_DT`             DATETIME     NOT NULL COMMENT '이벤트 종료일시',
    `RANK_PROBABILITIES` JSON         NOT NULL COMMENT '등수 비율',
    `EVENT_STATUS`       VARCHAR(64)  NOT NULL COMMENT '이벤트 상태',
    `CREATED_AT`         DATETIME     NOT NULL COMMENT '생성일시',
    `UPDATED_AT`         DATETIME     NOT NULL COMMENT '수정일시',
    PRIMARY KEY (`EVENT_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '이벤트';

DROP TABLE IF EXISTS EVENT_PRODUCTS;
CREATE TABLE EVENT_PRODUCTS (
    EVENT_PRODUCT_ID   BIGINT       NOT NULL AUTO_INCREMENT COMMENT '이벤트 상품 ID',
    EVENT_PRODUCT_NAME VARCHAR(100) NOT NULL COMMENT '이벤트 상품 이름',
    MAX_QUANTITY       INTEGER      NOT NULL COMMENT '최대 판매 가능 수량',
    PRODUCT_ID         BIGINT       NOT NULL COMMENT '상품 ID',
    EVENT_ID           BIGINT       NOT NULL COMMENT '이벤트 ID',
    CREATED_AT         DATETIME     NOT NULL COMMENT '생성일시',
    UPDATED_AT         DATETIME     NOT NULL COMMENT '수정일시',
    PRIMARY KEY (EVENT_PRODUCT_ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '이벤트 상품';

DROP TABLE IF EXISTS `EVENT_PRODUCT_STOCKS`;
CREATE TABLE `EVENT_PRODUCT_STOCKS` (
    `EVENT_PRODUCT_STOCK_ID` BIGINT   NOT NULL AUTO_INCREMENT COMMENT '이벤트 상품 재고 ID',
    `EVENT_PRODUCT_ID`       BIGINT   NOT NULL COMMENT '이벤트 상품 ID',
    `STOCK_QUANTITY`         INTEGER  NOT NULL COMMENT '현재 재고 수량',
    `VERSION`                BIGINT   NOT NULL DEFAULT 0 COMMENT '버전',
    `CREATED_AT`             DATETIME NOT NULL COMMENT '생성일시',
    `UPDATED_AT`             DATETIME NOT NULL COMMENT '수정일시',
    PRIMARY KEY (`EVENT_PRODUCT_STOCK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='이벤트 상품 재고';

